name: CI/CD React App

on:
    push:
        branches:
            - master # Change this to your main branch name

env:
    DEPLOY_PATH: /var/www
    BUILD_SCRIPT: npm run build
    BUILD_SCRIPT_OUTPUT: build

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: Production
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USER }}
                  password: ${{ secrets.DOCKERHUB_PASS }}
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3.0.0

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: arhontes/achieves:latest

            - name: Deploy to Server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: 22
                  script: |
                      docker pull arhontes/achieves:latest
                      docker run -d -p 80:80 arhontes/achieves:latest
