name: CI/CD React App

on:
  push:
    branches:
      - master  # Change this to your main branch name

env:
  DEPLOY_PATH: /var/www
  BUILD_SCRIPT: npm run build
  BUILD_SCRIPT_OUTPUT: build

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ${{ env.BUILD_SCRIPT_OUTPUT }}
        target: ${{ env.DEPLOY_PATH }}
