name: CI/CD React App

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: 195.93.253.24
        username: root
        key: '-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEA6aITj+kHVWIivmDUrM+tEpURc3NiMPEQ/KdgaaCyrHV0KLQMc2nz
sbRMF3BMWmx3rshfIxFgc0qfiT5Nk4wNSA1cv1sqLtWxrSr0N33CBektPe0ERbvFE3Hgst
xb7P0Ewo69DvM9q9xWhdmFz+gtnTKk5nyZuFvXxPOUhdhtQ8wHxTI+nc9sVJjdyO3I+Ws2
RR0L+3t/kdBVsfl5kjvKBFiH/FKMRr3enVDW8BGk0JyGrNdesaXFn5wT90623WLWKIkOQg
sVPjYzqGhD6CyxNQZNeG9qTQmBsjWQIb5mf8vJZbyCtHQe74npmCIMHHTqfe7y2AtF0Nub
2/m3fCHgnKpg2VxpHNDnLqVMMxPrlh9JLxR9lQuHEBtwzL6skUQsVoHX0hACsDpKp8orHw
0hfgpEg0Qx5aVTUpfmXGviJtSOCNe4TXKHg3iOvTyyrsM+jH+u7X/DlUIWAzA3SfVw2GKO
wE+I8jrNren+yeG0JxZ95+vK1fyUH1k6FEeDrrE5AAAFiFWqugxVqroMAAAAB3NzaC1yc2
EAAAGBAOmiE4/pB1ViIr5g1KzPrRKVEXNzYjDxEPynYGmgsqx1dCi0DHNp87G0TBdwTFps
d67IXyMRYHNKn4k+TZOMDUgNXL9bKi7Vsa0q9Dd9wgXpLT3tBEW7xRNx4LLcW+z9BMKOvQ
7zPavcVoXZhc/oLZ0ypOZ8mbhb18TzlIXYbUPMB8UyPp3PbFSY3cjtyPlrNkUdC/t7f5HQ
VbH5eZI7ygRYh/xSjEa93p1Q1vARpNCchqzXXrGlxZ+cE/dOtt1i1iiJDkILFT42M6hoQ+
gssTUGTXhvak0JgbI1kCG+Zn/LyWW8grR0Hu+J6ZgiDBx06n3u8tgLRdDbm9v5t3wh4Jyq
YNlcaRzQ5y6lTDMT65YfSS8UfZULhxAbcMy+rJFELFaB19IQArA6SqfKKx8NIX4KRINEMe
WlU1KX5lxr4ibUjgjXuE1yh4N4jr08sq7DPox/ru1/w5VCFgMwN0n1cNhijsBPiPI6za3p
/snhtCcWfefrytX8lB9ZOhRHg66xOQAAAAMBAAEAAAGAZFZ5NEsOHTtiVITdkcI3QE3JCt
45A2/krb1siLC9S5e95WU+G6sbP+yA6WgPQp5m4CepxDPISnt3/MdHJeD2K0Wh2YTbnvWj
sw1JiTN3SnaUOY47UX+M6gb0S5yb1jHsA2quA2evysl8V0vOTjYWsPZ5H4vPsP+wsSMzXD
BQ7NcJV0V24uucSNDGH28P6x6CVjhdVwn5BbSFuUO9VHJdFnS3IkSJfjA5FTMMvFm3gOhY
Zo6wWncpYpzzbjjeDEJPiUCxot275k0WJk6tiWlxaGkDvAhOKybS8oIDxHX3aaID13feD9
9E+BdsAhNg5I5mWDbn0QlCvLLGAOQs8d/8sVraOVsQsaPUZe1QFeFA9fr0dCjAFffarbSd
aT8aJKWuwcK4vHWSXKS8OZqdtUcW9Yo6swLZp6O8z+XpFQZxjOl3ph6Y2JMtu14NQpBZqM
CMltHRZcq1rKt4ManZ4m533UqwzmG0jMlMlwI6j5vXiJp/nwFgjt6hskZOvNo4FHoJAAAA
wQC/nIi7f51T1lAVMCE9bibl9q8Tl/WA8dVGjy7WMbBnxsGbnWXq0L62k/R0Pvg9368JSy
cvHpghXO+6AbbSF/NMDW4GdxA7dyvuzZBvs8xVSYDN3PRFhMFzGOvW2N/OTZF8G7mI2GjX
eyvSsADCwNc9M04ZMahZasmPsXUikMePn0Dg9VfIIUgQAA1G/3xiDP13Af3YIgDujxfEM5
deMIULcaslv+RRUK4Xet4ZdKp3tpwiNRm0WBYXCiJLEHcfa7oAAADBAPtIs415kMw+7zV/
qX54/SBHn7FAnF+Ikg6G/m+MlhstbyM2DVQVKmdEd8eSBU14Xv7Zy31ewd4XVshnYEFLGD
AhKxEpI7Vl9kTJqdtUBFFVMYqkyfA4mE6tQ7n2Y4n7Kz92p3w/ss4yeLC3xFxk2owb7v4v
laxYOvLbbGoF6cBLIIfLKtHBZZMcplaHMYGWMQuNmMeF2DGz5q1vANkWyEHMRNZZNkRlLe
a5gYwk/sKAQdibRj9JjcDUCKrEbvs00wAAAMEA7gSSMQSRTkjeE4IZXbk1M3vKKhq4SRqT
QQrUpv3OuR7Nk5FzNs+V2sy1/6VpBYd11/z6UGwx0SLfxkuUbGaO7btLGY5oKQlYxHElDS
xQM1hb8FqibcLBTPXxSAEQgwC4HQPadq6K1mowPspx0kapreeQnFUgjtJpdDZrQiIYUCvG
rfEcsG1Qcq4pQ6P8GaxpuArFAKEifqGWManlZeXAEyctlLu9ayXsnQ1LN7+pzSEjUyOgeR
eK3Put2GUTXepDAAAAC3Jvb3RAc3RhdGljAQIDBAUGBw==
-----END OPENSSH PRIVATE KEY-----'
        script: |
          sudo cp -r /root/rpg-life/build/* /var/www/build
